---
- hosts: "{{remote}}"
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  become: yes
  become_user: "{{ analytics_user }}"
  environment:
    AWS_STORAGE_ACCOUNT: "{{sunbird_private_storage_account_name}}"
    AWS_STORAGE_KEY: "{{sunbird_private_storage_account_key}}"
  roles:
   - lern-data-products-deploy
